apiVersion: v1
kind: Service
metadata:
  name: atena-api-service
spec:
  type: NodePort
  selector:
    app: atena-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
      name: uvicorn-port
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900
      name: minio-port
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30404
      name: spark-ui-port
    - protocol: TCP
      port: 7079
      targetPort: 7079
      nodePort: 30709
      name: spark-bm-port

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-atena-api-to-minio
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: atena-api
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.1.175/32
    ports:
    - protocol: TCP
      port: 9000
